import type { LanguageCode } from "@/lib/languages";

// Interface language. The R16 team uses Portuguese; guests (Paraguayan
// clients) see Spanish by default, and English when they speak any other
// language (an English-speaking guest can't use a Spanish screen). Only the
// screens guests can reach need these; team-only screens are written in
// Portuguese directly.
export type UiLang = "pt" | "es" | "en";

export function uiLangFor(spokenLanguage: LanguageCode): UiLang {
  if (spokenLanguage === "pt" || spokenLanguage === "es") return spokenLanguage;
  return "en";
}

const LANGUAGE_NAMES: Record<UiLang, Record<LanguageCode, string>> = {
  pt: {
    en: "Inglês",
    es: "Espanhol",
    pt: "Português",
    fr: "Francês",
    de: "Alemão",
    it: "Italiano",
    ja: "Japonês",
    ko: "Coreano",
    zh: "Chinês",
    ar: "Árabe",
  },
  es: {
    en: "Inglés",
    es: "Español",
    pt: "Portugués",
    fr: "Francés",
    de: "Alemán",
    it: "Italiano",
    ja: "Japonés",
    ko: "Coreano",
    zh: "Chino",
    ar: "Árabe",
  },
  en: {
    en: "English",
    es: "Spanish",
    pt: "Portuguese",
    fr: "French",
    de: "German",
    it: "Italian",
    ja: "Japanese",
    ko: "Korean",
    zh: "Chinese",
    ar: "Arabic",
  },
};

export function languageName(code: LanguageCode, lang: UiLang): string {
  return LANGUAGE_NAMES[lang][code] ?? code.toUpperCase();
}

const TEXT = {
  pt: {
    joinEyebrow: "[ ENTRAR NA REUNIÃO ]",
    joinTitle: "Reunião R16",
    joinSubtitle: "Informe seu nome e os idiomas",
    yourName: "Seu nome",
    yourNamePlaceholder: "Digite seu nome",
    iSpeak: "Eu vou falar em",
    iHear: "Quero ouvir em",
    selectLanguage: "Escolha o idioma",
    loading: "Carregando...",
    joining: "Entrando...",
    joinCall: "Entrar na chamada",
    summary: (speak: string, hear: string) =>
      `Você vai falar em ${speak} e ouvir os outros em ${hear}`,
    joinFailed: "Não foi possível entrar na chamada",
    waitingTitle: "Aguardando o anfitrião",
    waitingText:
      "Avisamos a equipe que você quer entrar. Mantenha esta página aberta.",
    waitingCancel: "Desistir",
    entryDenied: "O anfitrião não autorizou a sua entrada.",
    roomLocked: "Esta reunião não aceita mais entradas.",
    invalidLink: "Este link não é válido ou a reunião já terminou.",
    joiningCall: "Entrando na chamada...",
    hearingIn: (language: string) => `Ouvindo em ${language}`,
    shareLink: "Compartilhar link da reunião",
    mute: "Desligar microfone",
    unmute: "Ligar microfone",
    cameraOff: "Desligar câmera",
    cameraOn: "Ligar câmera",
    leave: "Sair da chamada",
    speaking: "falando...",
    waitingForSpeech: "Aguardando fala...",
    translating: "traduzindo...",
    transcriptTitle: "Transcrição ao vivo",
    allSpeakers: "Todos",
    transcriptShow: "Mostrar transcrição",
    transcriptHide: "Esconder transcrição",
    agentTitle: "Agente de IA",
    agentClear: "Limpar conversa com o agente",
    transcriptEmptyHint: "O que cada pessoa falar aparece aqui, na sua língua",
    askAgent: "Pergunte sobre a reunião...",
    secondsAgo: (s: number) => `há ${s} s`,
    minutesAgo: (m: number) => `há ${m} min`,
    captionsShow: "Mostrar legenda",
    captionsHide: "Esconder legenda",
    floorTake: "Falar",
    floorRelease: "Terminei",
    floorBusy: (name: string) => `${name} está falando`,
    floorHolder: (name: string) => `${name} está com a palavra`,
    floorYouHold: "Você está com a palavra. Clique em Terminei quando acabar.",
    floorFree: "Para falar, clique em Falar",
    floorLockOn: "Trava de fala ligada (clique para desligar)",
    floorLockOff: "Trava de fala desligada (clique para ligar)",
    captionsError:
      "A transcrição não está funcionando. Tente sair e entrar de novo.",
    yourVoice: "Sua voz na tradução",
    voiceFemale: "Feminina",
    voiceMale: "Masculina",
    voiceOn: "Ouvindo a tradução por voz (clique para desligar)",
    voiceOff: "Tradução por voz desligada (clique para ouvir)",
    floorWaitVoice: "Aguarde a tradução",
    screenShare: "Compartilhar tela",
    screenShareStop: "Parar de compartilhar",
    screenShareBusy: (name: string) =>
      `${name || "Alguém"} já está compartilhando a tela`,
    screenSharedBy: (name: string) =>
      `${name || "Alguém"} está compartilhando a tela`,
    screenSharingYou: "Você está compartilhando a sua tela",
    changeLanguages: "Trocar os idiomas (falo / ouço)",
    recordingCloud: "Esta reunião está sendo gravada",
    recordingLocal: (names: string) => `Gravando no computador de ${names}`,
    recordingYou: "você",
    voiceHear: "Ouvir a tradução por voz",
    voiceTranslatedVolume: "Voz traduzida",
    voiceOriginalVolume: "Voz original enquanto a tradução toca",
    voiceHeadphones:
      "Sem fone de ouvido, as vozes podem voltar pelo seu microfone (eco). Com fone fica melhor.",
    done: "Pronto",
    micOff: "Microfone desligado",
  },
  es: {
    joinEyebrow: "[ UNIRSE A LA REUNIÓN ]",
    joinTitle: "Reunión R16",
    joinSubtitle: "Escribe tu nombre y elige los idiomas",
    yourName: "Tu nombre",
    yourNamePlaceholder: "Escribe tu nombre",
    iSpeak: "Voy a hablar en",
    iHear: "Quiero escuchar en",
    selectLanguage: "Elige el idioma",
    loading: "Cargando...",
    joining: "Entrando...",
    joinCall: "Unirse a la llamada",
    summary: (speak: string, hear: string) =>
      `Vas a hablar en ${speak} y escuchar a los demás en ${hear}`,
    joinFailed: "No fue posible unirse a la llamada",
    waitingTitle: "Esperando al anfitrión",
    waitingText:
      "Avisamos al equipo que quieres entrar. Mantén esta página abierta.",
    waitingCancel: "Cancelar",
    entryDenied: "El anfitrión no autorizó tu entrada.",
    roomLocked: "Esta reunión ya no acepta nuevas entradas.",
    invalidLink: "Este enlace no es válido o la reunión ya terminó.",
    joiningCall: "Entrando a la llamada...",
    hearingIn: (language: string) => `Escuchando en ${language}`,
    shareLink: "Compartir enlace de la reunión",
    mute: "Apagar micrófono",
    unmute: "Encender micrófono",
    cameraOff: "Apagar cámara",
    cameraOn: "Encender cámara",
    leave: "Salir de la llamada",
    speaking: "hablando...",
    waitingForSpeech: "Esperando que alguien hable...",
    translating: "traduciendo...",
    transcriptTitle: "Transcripción en vivo",
    allSpeakers: "Todos",
    transcriptShow: "Mostrar transcripción",
    transcriptHide: "Ocultar transcripción",
    agentTitle: "Agente de IA",
    agentClear: "Borrar conversación con el agente",
    transcriptEmptyHint: "Lo que diga cada persona aparece aquí, en tu idioma",
    askAgent: "Pregunta sobre la reunión...",
    secondsAgo: (s: number) => `hace ${s} s`,
    minutesAgo: (m: number) => `hace ${m} min`,
    captionsShow: "Mostrar subtítulos",
    captionsHide: "Ocultar subtítulos",
    floorTake: "Hablar",
    floorRelease: "Terminé",
    floorBusy: (name: string) => `${name} está hablando`,
    floorHolder: (name: string) => `${name} tiene la palabra`,
    floorYouHold: "Tienes la palabra. Haz clic en Terminé cuando acabes.",
    floorFree: "Para hablar, haz clic en Hablar",
    floorLockOn: "Turno de palabra activado (clic para desactivar)",
    floorLockOff: "Turno de palabra desactivado (clic para activar)",
    captionsError:
      "La transcripción no está funcionando. Intenta salir y volver a entrar.",
    yourVoice: "Tu voz en la traducción",
    voiceFemale: "Femenina",
    voiceMale: "Masculina",
    voiceOn: "Escuchando la traducción por voz (clic para apagar)",
    voiceOff: "Traducción por voz apagada (clic para escuchar)",
    floorWaitVoice: "Espera la traducción",
    screenShare: "Compartir pantalla",
    screenShareStop: "Dejar de compartir",
    screenShareBusy: (name: string) =>
      `${name || "Alguien"} ya está compartiendo la pantalla`,
    screenSharedBy: (name: string) =>
      `${name || "Alguien"} está compartiendo la pantalla`,
    screenSharingYou: "Estás compartiendo tu pantalla",
    changeLanguages: "Cambiar los idiomas (hablo / escucho)",
    recordingCloud: "Esta reunión se está grabando",
    recordingLocal: (names: string) => `Grabando en la computadora de ${names}`,
    recordingYou: "ti",
    voiceHear: "Escuchar la traducción por voz",
    voiceTranslatedVolume: "Voz traducida",
    voiceOriginalVolume: "Voz original mientras suena la traducción",
    voiceHeadphones:
      "Sin auriculares, las voces pueden volver por tu micrófono (eco). Con auriculares es mejor.",
    done: "Listo",
    micOff: "Micrófono apagado",
  },
  en: {
    joinEyebrow: "[ JOIN THE MEETING ]",
    joinTitle: "R16 Meeting",
    joinSubtitle: "Enter your name and choose the languages",
    yourName: "Your name",
    yourNamePlaceholder: "Type your name",
    iSpeak: "I will speak",
    iHear: "I want to hear",
    selectLanguage: "Choose the language",
    loading: "Loading...",
    joining: "Joining...",
    joinCall: "Join the call",
    summary: (speak: string, hear: string) =>
      `You will speak ${speak} and hear the others in ${hear}`,
    joinFailed: "Could not join the call",
    waitingTitle: "Waiting for the host",
    waitingText: "We told the team you want to join. Keep this page open.",
    waitingCancel: "Cancel",
    entryDenied: "The host did not let you in.",
    roomLocked: "This meeting no longer accepts new people.",
    invalidLink: "This link is not valid or the meeting has ended.",
    joiningCall: "Joining the call...",
    hearingIn: (language: string) => `Hearing in ${language}`,
    shareLink: "Share the meeting link",
    mute: "Turn microphone off",
    unmute: "Turn microphone on",
    cameraOff: "Turn camera off",
    cameraOn: "Turn camera on",
    leave: "Leave the call",
    speaking: "speaking...",
    waitingForSpeech: "Waiting for someone to speak...",
    translating: "translating...",
    transcriptTitle: "Live transcript",
    allSpeakers: "Everyone",
    transcriptShow: "Show transcript",
    transcriptHide: "Hide transcript",
    agentTitle: "AI agent",
    agentClear: "Clear the conversation with the agent",
    transcriptEmptyHint:
      "What each person says shows up here, in your language",
    askAgent: "Ask about the meeting...",
    secondsAgo: (s: number) => `${s} s ago`,
    minutesAgo: (m: number) => `${m} min ago`,
    captionsShow: "Show captions",
    captionsHide: "Hide captions",
    floorTake: "Speak",
    floorRelease: "Done",
    floorBusy: (name: string) => `${name} is speaking`,
    floorHolder: (name: string) => `${name} has the floor`,
    floorYouHold: "You have the floor. Click Done when you finish.",
    floorFree: "To speak, click Speak",
    floorLockOn: "Turn-taking on (click to turn off)",
    floorLockOff: "Turn-taking off (click to turn on)",
    captionsError:
      "The transcription is not working. Try leaving and joining again.",
    yourVoice: "Your voice in the translation",
    voiceFemale: "Female",
    voiceMale: "Male",
    voiceOn: "Hearing the spoken translation (click to turn off)",
    voiceOff: "Spoken translation off (click to hear it)",
    floorWaitVoice: "Wait for the translation",
    screenShare: "Share screen",
    screenShareStop: "Stop sharing",
    screenShareBusy: (name: string) =>
      `${name || "Someone"} is already sharing their screen`,
    screenSharedBy: (name: string) =>
      `${name || "Someone"} is sharing their screen`,
    screenSharingYou: "You are sharing your screen",
    changeLanguages: "Change the languages (I speak / I hear)",
    recordingCloud: "This meeting is being recorded",
    recordingLocal: (names: string) => `Recording on ${names}'s computer`,
    recordingYou: "your",
    voiceHear: "Hear the spoken translation",
    voiceTranslatedVolume: "Translated voice",
    voiceOriginalVolume: "Original voice while the translation plays",
    voiceHeadphones:
      "Without headphones, voices may come back through your microphone (echo). Headphones work better.",
    done: "Done",
    micOff: "Microphone off",
  },
} satisfies Record<UiLang, Record<string, unknown>>;

export type UiText = (typeof TEXT)["pt"];

export function uiText(lang: UiLang): UiText {
  return TEXT[lang];
}
