import { after } from "next/server";
import { z } from "zod";

import { db } from "@/db";
import { transcripts } from "@/db/schema";
import { translateCaption } from "@/lib/caption-translation";
import { isValidLanguageCode, type LanguageCode } from "@/lib/languages";
import { getRoomAccess } from "@/lib/room-access";
import { getActiveTranslationProvider } from "@/lib/translation-providers";

// A piece of speech from the speaker's browser, saved in the meeting
// transcript (after answering, so the database never slows captions down).
//
// - ElevenLabs provider: the piece is translated here (OpenAI) into the
//   languages the others want; the speaker then shares the translations
//   through Daily.
// - Soniox provider: Soniox already translated it in the browser; the
//   translations come in the request and are only saved.

const languageCode = z.string().refine(isValidLanguageCode);

const CaptionSchema = z.object({
  invite: z.string().max(100).nullish(),
  // Generated by the speaker's browser; also the transcript row id
  id: z.string().regex(/^[A-Za-z0-9_-]{8,32}$/),
  text: z.string().trim().min(1).max(2000),
  language: languageCode,
  targets: z.array(languageCode).max(5),
  // The last few pieces of the meeting, oldest first, so short pieces make
  // sense to the translator (sent by the browser to skip a database read)
  context: z.array(z.string().max(500)).max(6).default([]),
  speakerName: z.string().trim().min(1).max(60),
  visitorId: z.string().min(1).max(100),
  // Soniox: translations made in the browser, by language
  translations: z
    .record(languageCode, z.string().max(2000))
    .refine((value) => Object.keys(value).length <= 5)
    .optional(),
});

export async function POST(
  req: Request,
  { params }: { params: Promise<{ roomId: string }> },
) {
  const { roomId } = await params;
  const parsed = CaptionSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return Response.json({ error: "Dados inválidos" }, { status: 400 });
  }
  const caption = parsed.data;

  // Only while captions are on, and only for people who may use the room
  // (ElevenLabs translation spends OpenAI credits)
  const [provider, access] = await Promise.all([
    getActiveTranslationProvider(),
    getRoomAccess(roomId, caption.invite),
  ]);
  if (provider !== "elevenlabs" && provider !== "soniox") {
    return Response.json({ error: "Legendas desativadas" }, { status: 409 });
  }
  if (!access) {
    return Response.json({ error: "Não autorizado" }, { status: 401 });
  }
  const { room } = access;
  const from = caption.language as LanguageCode;

  const targets = [...new Set(caption.targets)].filter(
    (target) => target !== from,
  ) as LanguageCode[];

  // One failed language must not lose the others (or the original)
  const results = await Promise.all(
    targets.map(async (to) => {
      if (provider === "soniox") {
        const text = caption.translations?.[to]?.trim();
        return text ? ([to, text] as const) : null;
      }
      try {
        const text = await translateCaption({
          text: caption.text,
          from,
          to,
          context: caption.context,
        });
        return text ? ([to, text] as const) : null;
      } catch (error) {
        console.error(`[captions] translation to ${to} failed:`, error);
        return null;
      }
    }),
  );
  const translations: Record<string, string> = Object.fromEntries(
    results.filter((entry) => entry !== null),
  );

  after(async () => {
    try {
      await db
        .insert(transcripts)
        .values({
          id: caption.id,
          roomId: room.id,
          participantId: `${caption.visitorId}_${room.id}`,
          speakerName: caption.speakerName,
          originalText: caption.text,
          originalLanguage: from,
          translatedTexts: translations,
        })
        .onConflictDoNothing();
    } catch (error) {
      // The captions still work without the saved transcript
      console.error("[captions] failed to save transcript:", error);
    }
  });

  return Response.json({ translations });
}
