import { desc, eq } from "drizzle-orm";
import { z } from "zod";

import { db } from "@/db";
import { transcripts } from "@/db/schema";
import { translateCaption } from "@/lib/caption-translation";
import { isValidLanguageCode, type LanguageCode } from "@/lib/languages";
import { getRoomAccess } from "@/lib/room-access";
import { getActiveTranslationProvider } from "@/lib/translation-providers";

// A piece of speech from the speaker's browser (ElevenLabs provider):
// translate it into the languages the others want to hear, save it in the
// meeting transcript and send the translations back. The speaker then
// shares them with everyone through Daily.

const languageCode = z.string().refine(isValidLanguageCode);

const CaptionSchema = z.object({
  invite: z.string().max(100).nullish(),
  // Generated by the speaker's browser; also the transcript row id
  id: z.string().regex(/^[A-Za-z0-9_-]{8,32}$/),
  text: z.string().trim().min(1).max(2000),
  language: languageCode,
  targets: z.array(languageCode).max(5),
  speakerName: z.string().trim().min(1).max(60),
  visitorId: z.string().min(1).max(100),
});

// Earlier pieces given to the translator so short pieces make sense
const CONTEXT_PHRASES = 6;

export async function POST(
  req: Request,
  { params }: { params: Promise<{ roomId: string }> },
) {
  const { roomId } = await params;
  const parsed = CaptionSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return Response.json({ error: "Dados inválidos" }, { status: 400 });
  }
  const caption = parsed.data;

  // Translation spends OpenAI credits: only while ElevenLabs is the provider
  if ((await getActiveTranslationProvider()) !== "elevenlabs") {
    return Response.json({ error: "Legendas desativadas" }, { status: 409 });
  }

  const access = await getRoomAccess(roomId, caption.invite);
  if (!access) {
    return Response.json({ error: "Não autorizado" }, { status: 401 });
  }
  const { room } = access;
  const from = caption.language as LanguageCode;

  const earlier = await db
    .select({ text: transcripts.originalText })
    .from(transcripts)
    .where(eq(transcripts.roomId, room.id))
    .orderBy(desc(transcripts.timestamp))
    .limit(CONTEXT_PHRASES);
  const context = earlier.map((row) => String(row.text)).reverse();

  const targets = [...new Set(caption.targets)].filter(
    (target) => target !== from,
  ) as LanguageCode[];

  // One failed language must not lose the others (or the original)
  const results = await Promise.all(
    targets.map(async (to) => {
      try {
        const text = await translateCaption({
          text: caption.text,
          from,
          to,
          context,
        });
        return text ? ([to, text] as const) : null;
      } catch (error) {
        console.error(`[captions] translation to ${to} failed:`, error);
        return null;
      }
    }),
  );
  const translations: Record<string, string> = Object.fromEntries(
    results.filter((entry) => entry !== null),
  );

  try {
    await db
      .insert(transcripts)
      .values({
        id: caption.id,
        roomId: room.id,
        participantId: `${caption.visitorId}_${room.id}`,
        speakerName: caption.speakerName,
        originalText: caption.text,
        originalLanguage: from,
        translatedTexts: translations,
      })
      .onConflictDoNothing();
  } catch (error) {
    // The captions still work without the saved transcript
    console.error("[captions] failed to save transcript:", error);
  }

  return Response.json({ translations });
}
